title: UNCC Computer Vision Lab
description: Research in computer vision at UNC Charlotte.
theme: minima
markdown: kramdown
plugins:
  - jekyll-seo-tag
defaults:
  - scope: { path: "" }
    values: { layout: default }
